### ISSUE TITLE
Add repository name to the card

### ISSUE THREAD

**Issue by cowlike** [tomkalesse/publish-release-notes#1]
I see you're adding a clickable link to the repo on the card but the name of the repository doesn't appear anywhere on the card. Can this be added - maybe as part of the title, or prefixed on the notes? It would be very helpful when you have multiple repos publishing to a single channel, which is exactly the use case we have on our team.

**Comment by tomkalesse** [comment]
Thank you for your suggestion! 
I have added the repository full_name to the release card for Microsoft Teams. It is now available in v2. If this is what you expected fell free to close this issue!

**Comment by cowlike** [comment]
Perfect, thanks!
